<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
<!-- Верхние строки объявляют версию XML и указывают на внешний файл стилей CSS. -->

<!DOCTYPE products [
    <!-- Следующие строки определяют сущности для различных типов данных. -->
    <!ENTITY % category "CDATA">
    <!ENTITY % brand "CDATA">
    <!ENTITY % price "CDATA">
    <!ENTITY % name "CDATA">

    <!-- Следующие строки определяют структуру XML-документа. -->
    <!ELEMENT products (product+)>
    <!ELEMENT product (name, price, brand, category)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT brand (#PCDATA)>
    <!ELEMENT category (#PCDATA)>

    <!-- Следующая строка определяет атрибут для элемента 'product'. -->
    <!ATTLIST product
        id ID #IMPLIED
    >
]>
<products>
    <!-- Следующие блоки представляют отдельные записи продуктов с вложенными элементами. -->
    <product>
        <name>Laptop</name>
        <price>1200</price>
        <brand>HP</brand>
        <category>Electronics</category>
    </product>
    <product>
        <name>Smartphone</name>
        <price>700</price>
        <brand>Samsung</brand>
        <category>Electronics</category>
    </product>
    <product>
        <name>Running Shoes</name>
        <price>80</price>
        <brand>Nike</brand>
        <category>Footwear</category>
    </product>
    <product>
        <name>HD TV</name>
        <price>1000</price>
        <brand>Sony</brand>
        <category>Electronics</category>
    </product>
    <product>
        <name>Backpack</name>
        <price>50</price>
        <brand>Adidas</brand>
        <category>Accessories</category>
    </product>
</products>
